version: '3'

services:
  app:
    build: . #points to dockerfile
    entrypoint: dockerize -wait tcp://db:3306 -timeout 120s ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    build: ./.docker/mysql
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root